openapi: 3.0.3
info:
  title: BaSyx Company Lookup API
  description: Company Lookup (ComLookup) API for registering and discovering company components.
  contact:
    name: BaSyx Developers
    email: basyx-dev@eclipse.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: V1
servers:
  - url: 'https://example.com/'
paths:
  /companies:
    get:
      tags: [Company Lookup API]
      summary: Returns all Company Descriptors
      operationId: GetAllCompanyDescriptors
      parameters:
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Cursor'
        - $ref: '#/components/parameters/Name'
        - $ref: '#/components/parameters/AssetId'
      responses:
        '200':
          description: Paged list of Company Descriptors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedCompanyDescriptors'
              examples:
                companyDescriptor:
                  $ref: '#/components/examples/CompanyDescriptor'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
        'default':
          $ref: '#/components/responses/DefaultError'

    post:
      tags: [Company Lookup API]
      summary: Creates a new Company Descriptor
      operationId: PostCompanyDescriptor
      requestBody:
        description: Company Descriptor envelope object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyDescriptorEnvelope'
            examples:
              companyDescriptor:
                $ref: '#/components/examples/CompanyDescriptorSingleEnvelope'
      responses:
        '201':
          description: Company Descriptor created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyDescriptorEnvelope'
              examples:
                companyDescriptor:
                  $ref: '#/components/examples/CompanyDescriptorSingleEnvelope'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
        'default':
          $ref: '#/components/responses/DefaultError'

  /companies/{companyIdentifier}:
    parameters:
      - $ref: '#/components/parameters/CompanyIdentifier'
    get:
      tags: [Company Lookup API]
      summary: Returns a specific Company Descriptor
      operationId: GetCompanyDescriptorById
      responses:
        '200':
          description: Company Descriptor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyDescriptorEnvelope'
              examples:
                companyDescriptor:
                  $ref: '#/components/examples/CompanyDescriptorSingleEnvelope'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
        'default':
          $ref: '#/components/responses/DefaultError'

    put:
      tags: [Company Lookup API]
      summary: Updates an existing Company Descriptor
      operationId: PutCompanyDescriptorById
      requestBody:
        description: Company Descriptor envelope object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyDescriptorEnvelope'
            examples:
                companyDescriptor:
                  $ref: '#/components/examples/CompanyDescriptorSingleEnvelope'
      responses:
        '200':
          description: Company Descriptor updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyDescriptorEnvelope'
              examples:
                companyDescriptor:
                  $ref: '#/components/examples/CompanyDescriptorSingleEnvelope'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'
        'default':
          $ref: '#/components/responses/DefaultError'

    delete:
      tags: [Company Lookup API]
      summary: Deletes a Company Descriptor
      operationId: DeleteCompanyDescriptorById
      responses:
        '204':
          description: Company Descriptor deleted successfully
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
        'default':
          $ref: '#/components/responses/DefaultError'

  /description:
    get:
      tags: [Description API]
      summary: Returns the self-describing information of a network resource (ServiceDescription)
      operationId: GetDescription
      responses:
        '200':
          description: Service description
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceDescription'
              examples:
                descriptionResponse:
                  $ref: '#/components/examples/DescriptionResponse'
        '500':
          $ref: '#/components/responses/InternalServerError'
        'default':
          $ref: '#/components/responses/DefaultError'

components:
  parameters:
    Limit:
      name: limit
      in: query
      required: false
      description: The maximum number of elements in the response array
      schema:
        type: integer
        minimum: 1

    Cursor:
      name: cursor
      in: query
      required: false
      description: A server-generated identifier retrieved from paging_metadata that specifies from which position the result listing should continue
      schema:
        type: string

    Name:
      name: name
      in: query
      required: false
      description: Base64url encoded name filter (matches CompanyDescriptor.name or one of CompanyDescriptor.nameOptions)
      schema:
        type: string

    AssetId:
      name: assetId
      in: query
      required: false
      description: Base64url encoded asset id used to match CompanyDescriptor.assetIdRegexPatterns
      schema:
        type: string

    CompanyIdentifier:
      name: companyIdentifier
      in: path
      required: true
      description: Company domain identifier (base64url-encoded domain)
      schema:
        type: string

  responses:
    BadRequest:
      description: Bad Request, e.g. the request parameters of the format of the request body is wrong.
      content:
        application/json:
          examples:
            errorResponse:
              $ref: "#/components/examples/ErrorResponse"
          schema:
              $ref: "#/components/schemas/Result"

    NotFound:
      description: Not Found
      content:
        application/json:
          examples:
            errorResponse:
              $ref: "#/components/examples/ErrorResponse"

    Conflict:
      description: Conflict
      content:
        application/json:
          examples:
            errorResponse:
              $ref: "#/components/examples/ErrorResponse"

    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          examples:
            errorResponse:
              $ref: "#/components/examples/ErrorResponse"

    DefaultError:
      description: Default error handling for unmentioned status codes
      content:
        application/json:
          examples:
            errorResponse:
              $ref: "#/components/examples/ErrorResponse"

  schemas:
    ServiceDescription:
      type: object
      description: "The Description object enables servers to present their capabilities to the clients, in particular which profiles they implement. At least one defined profile is required. Additional, proprietary attributes might be included. Nevertheless, the server must not expect that a regular client understands them."
      additionalProperties: false
      properties:
        profiles:
          type: array
          minItems: 1
          items:
            type: string
            example: "TODO"
      example:
        profiles:
          - TODO

    PagedCompanyDescriptors:
      type: object
      additionalProperties: false
      properties:
        paging_metadata:
          $ref: "#/components/schemas/PagingMetadata"
        data:
          type: array
          items:
            $ref: "#/components/schemas/CompanyDescriptor"
      required: [paging_metadata, data]

    PagingMetadata:
      type: object
      additionalProperties: false
      properties:
        cursor:
          type: string
          description: Cursor to request the next page (base64url-encoded)

    CompanyDescriptor:
      type: object
      additionalProperties: false
      properties:
        idShort:
          type: string
        name:
          type: string
        domain:
          type: string
        nameOptions:
          type: array
          items:
            type: string
        assetIdRegexPatterns:
          type: array
          items:
            type: string
        description:
          type: array
          items:
            $ref: "#/components/schemas/LangStringTextType"
        displayName:
          type: array
          items:
            $ref: "#/components/schemas/LangStringTextType"
        administration:
          $ref: "#/components/schemas/AdministrativeInformation"
        endpoints:
          type: array
          items:
            $ref: "#/components/schemas/Endpoint"
      required: [domain, endpoints]

    CompanyDescriptorEnvelope:
      type: object
      additionalProperties: false
      properties:
        data:
          $ref: "#/components/schemas/CompanyDescriptor"
      required: [data]

    LangStringTextType:
      type: object
      additionalProperties: false
      properties:
        language:
          type: string
        text:
          type: string
      required: [language, text]

    Endpoint:
      type: object
      additionalProperties: false
      properties:
        protocolInformation:
          $ref: "#/components/schemas/ProtocolInformation"
        interface:
          type: string
      required: [protocolInformation, interface]

    ProtocolInformation:
      type: object
      additionalProperties: false
      properties:
        href:
          type: string
        endpointProtocol:
          type: string
      required: [href, endpointProtocol]

    AdministrativeInformation:
      type: object
      additionalProperties: false
      properties:
        version:
          type: string
        revision:
          type: string
        creator:
          $ref: "#/components/schemas/Reference"

    Reference:
      type: array
      additionalProperties: false
      properties:
        type:
          type: string
        keys:
          type: array
          items:
            $ref: "#/components/schemas/Key"
      required: [type, keys]

    Key:
      type: object
      additionalProperties: false
      properties:
        type:
          type: string
        value:
          type: string
      required: [type, value]

    Result:
      type: object
      additionalProperties: false
      properties:
        messages:
          type: array
          items: 
            $ref: "#/components/schemas/Message"
    
    Message:
      type: object
      properties:
        code:
          type: string
          maxLength: 32
          minLength: 1
        correlationId:
          type: string
          maxLength: 128
          minLength: 1
        messageType:
          enum:
            0: Undefined
            1: info
            2: Warning
            3: Error
            4: Exception
          type: string
        text:
          type: string
        timestamp:
          type: string
          pattern: ^-?(([1-9][0-9][0-9][0-9]+)|(0[0-9][0-9][0-9]))-((0[1-9])|(1[0-2]))-((0[1-9])|([12][0-9])|(3[01]))T(((([01][0-9])|(2[0-3])):[0-5][0-9]:([0-5][0-9])(\\.[0-9]+)?)|24:00:00(\\.0+)?)(Z|\\+00:00|-00:00)$

  examples:
    CompanyDescriptor:
      value:
        paging_metadata:
          cursor: "ZXhhbXBsZS5jb21wYW55Mi5jb20"
        data:
          - administration:
              creator:
                keys:
                  - type: "GlobalReference"
                    value: "https://example.com"
                type: "ExternalReference"
              revision: "0"
              version: "1"
            name: "ExampleCompany"
            domain: "example.com"
            nameOptions:
              - "Example Company Inc"
              - "ExampleCo"
            assetIdRegexPatterns:
              - "^https://i\\.example\\.com/"
            description:
              - language: "en"
                text: "Example AAS Registry"
            displayName:
              - language: "en"
                text: "AAS Registry 1"
            endpoints:
              - interface: "AAS-REGISTRY-3.0"
                protocolInformation:
                    href: "https://example.com/aas-registry"
                    endpointProtocol: "HTTPS"
            idShort: "exampleCompany"

    CompanyDescriptorSingle:
      value:
        administration:
          creator:
            keys:
              - type: "GlobalReference"
                value: "https://example.com"
            type: "ExternalReference"
          revision: "0"
          version: "1"
        name: "ExampleCompany"
        domain: "example.com"
        nameOptions:
          - "Example Company Inc"
          - "ExampleCo"
        assetIdRegexPatterns:
          - "^https://i\\.example\\.com/"
        description:
          - language: "en"
            text: "Example AAS Registry"
        displayName:
          - language: "en"
            text: "AAS Registry 1"
        endpoints:
          - interface: "AAS-REGISTRY-3.0"
            protocolInformation:
                href: "https://example.com/aas-registry"
                endpointProtocol: "HTTPS"
        idShort: "exampleCompany"

    CompanyDescriptorSingleEnvelope:
      value:
        data:
          administration:
            creator:
              keys:
                - type: "GlobalReference"
                  value: "https://example.com"
              type: "ExternalReference"
            revision: "0"
            version: "1"
          name: "ExampleCompany"
          domain: "example.com"
          nameOptions:
            - "Example Company Inc"
            - "ExampleCo"
          assetIdRegexPatterns:
            - "^https://i\\.example\\.com/"
          description:
            - language: "en"
              text: "Example AAS Registry"
          displayName:
            - language: "en"
              text: "AAS Registry 1"
          endpoints:
            - interface: "AAS-REGISTRY-3.0"
              protocolInformation:
                  href: "https://example.com/aas-registry"
                  endpointProtocol: "HTTPS"
          idShort: "exampleCompany"

    DescriptionResponse:
      value:
        profiles:
          - "TODO"

    ErrorResponse:
      type: object
      value:
        messages:
          - code: "string"
            correlationId: "string"
            messageType: "Undefined"
            text: "string"
            timestamp: "1970-01-01T00:00:00.000Z"
